### ISSUE TITLE
程序在”查找空闲场地“的地方出错

### ISSUE THREAD

**Issue by dingning97** [yanyuandaxia/PKUAutoBookingVenues#1]
macOS Catalina         Chrome 96

代码在page_func.py的这一行出错：
https://github.com/yanyuandaxia/PKUAutoBookingVenues/blob/6a95057c71fa236602ec25cbf734c65b4285f9c1/page_func.py#L193

WebDriverWait(driver, 10).until(
        EC.visibility_of_element_located((By.XPATH, '/html/body/div[1]/div/div/div[3]/div[2]/div/div[2]/form/div/div/div/div[1]/div/div/input')))

请问大概是什么原因😂

<img width="1377" alt="截屏2021-12-15 下午6 39 08" src="https://user-images.githubusercontent.com/57791074/146171539-de0761a3-cc6a-4259-99ce-fba93fa57d4a.png">

**Comment by yanyuandaxia** [comment]
看起来，似乎是报了没找到某个元素的错误，就是10秒之内这个页面还没加载出来，是不是当时网断了或者网络环境不太好？

**Comment by yanyuandaxia** [comment]
啊，我明白了，你把场馆名称写成了”羽毛球场馆“，但是学校只有”羽毛球场“或者”羽毛球馆“，所以就找不到元素了

**Comment by dingning97** [comment]
谢谢老哥！run了一下可以正常预定。等下周4中午试试抢周日的场子嘿嘿
